on: [push, pull_request]
jobs:
    openapi_check:
      name: "OpenAPI check"
      runs-on: ubuntu-latest
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: "Generate deutschland code"
          uses: wirthual/deutschland-generator-action@v0.8.0
          with:
            openapi-file: "undefined"
            upload-to-pypi: false
            upload-to-testpypi: false
            pypi-token: "Pypi token here"
            testpypi-token: "TestPyPi token here"
            python-version: "3.7"
